set nocompatible              " be iMproved, required
filetype off                  " required

let mapleader=","

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

Plugin 'tpope/vim-fugitive'

Plugin 'po1/javacomplete'
autocmd FileType java setlocal omnifunc=javacomplete#Complete
autocmd FileType java map <leader>b :call javacomplete#GoToDefinition()<CR>
autocmd FileType java inoremap <buffer> . .<C-X><C-O>
let g:nailgun_port='2113'

Plugin 'airblade/vim-gitgutter'

Plugin 'scrooloose/syntastic'

Plugin 'majutsushi/tagbar'
nmap <leader>tt :TagbarToggle<CR>

Plugin 'scrooloose/nerdtree'
map <leader>n :NERDTreeToggle<CR>

Bundle 'mileszs/ack.vim'

Plugin 'tpope/vim-surround'

Plugin 'ervandew/supertab'

Plugin 'Raimondi/delimitMate'
let delimitMate_expand_cr = 1

Plugin 'kien/ctrlp.vim'

Plugin 'godlygeek/tabular'

Plugin 'tomasr/molokai'

Plugin 'airblade/vim-rooter'

Plugin 'bling/vim-airline'
set noshowmode
set laststatus=2

" Snippets
Plugin 'SirVer/ultisnips'

" " The following are examples of different formats supported.
" " Keep Plugin commands between vundle#begin/end.
" " plugin on GitHub repo
" Plugin 'tpope/vim-fugitive'
" " plugin from http://vim-scripts.org/vim/scripts.html
" Plugin 'L9'
" " Git plugin not hosted on GitHub
" Plugin 'git://git.wincent.com/command-t.git'
" " git repos on your local machine (i.e. when working on your own plugin)
" Plugin 'file:///home/gmarik/path/to/plugin'
" " The sparkup vim script is in a subdirectory of this repo called vim.
" " Pass the path to set the runtimepath properly.
" Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
" " Avoid a name conflict with L9
" Plugin 'user/L9', {'name': 'newL9'}

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

set t_Co=256
colorscheme molokai

map <leader>cf :lcd %:p:h<CR>

map <leader>ss :Ack! -w <cfile> src<CR>

set nowrap
set hlsearch
set ignorecase
set smartcase
set incsearch

set ai sw=4 ts=4 sta et
autocmd FileType c,python,java setlocal fo=croql
autocmd FileType xml setlocal sw=2 ts=2

set cot+=longest

set undodir=~/.vim/undo
set undofile

set colorcolumn=80,120
set list listchars=tab:»·,trail:•

set tags+=~/.tags

set rnu
autocmd InsertEnter * :set number
autocmd InsertLeave * :set relativenumber

if getcwd() =~ 'otter-home'
    source ~/.vim/otter-home.env.vim
endif
